run:
  timeout: 5m
  skip-files: [ ]
  skip-dirs: [ ]

linters:
  enable-all: true
  disable:
    - maligned
    - interfacer
    - scopelint
    - golint
    - sqlclosecheck
    - rowserrcheck
    - cyclop
    - lll
    - dupl
    - wsl
    - nlreturn
    - gomnd
    - goerr113
    - wrapcheck
    - exhaustive
    - exhaustivestruct
    - testpackage
    - tparallel
    - paralleltest
    - prealloc
    - ifshort
    - forcetypeassert
    - varnamelen
    - noctx

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 5
    min-occurrences: 3
  misspell:
    locale: US
  funlen:
    lines: -1
    statements: 40
  godox:
    keywords:
      - FIXME
  gofumpt:
    extra-rules: true
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/sirupsen/logrus
      - github.com/pkg/errors
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - sloppyReassign
      - rangeValCopy
      - octalLiteral
      - paramTypeCombine
    settings:
      hugeParam:
        sizeThreshold: 100
  gosec:
    excludes:
      - G307
      - G304

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude: [ ]
