// Code generated by internal/generator.go. DO NOT EDIT.

package mimetype

const (
	// HapticsIvs ivs mime type.
	HapticsIvs = "haptics/ivs"
	// HapticsHjif hjif mime type.
	HapticsHjif = "haptics/hjif"
	// HapticsHmpg hmpg mime type.
	HapticsHmpg = "haptics/hmpg"
)

// IsHaptics checks if the mime types is haptics.
func IsHaptics(mt string) bool {
	switch mt {
	case "haptics/hjif":
		return true
	case "haptics/hmpg":
		return true
	case "haptics/ivs":
		return true
	default:
		return false
	}
}
