// Code generated by internal/generator.go. DO NOT EDIT.

package mimetype

const (
	// Text1dInterleavedParityfec 1d-interleaved-parityfec mime type.
	Text1dInterleavedParityfec = "text/1d-interleaved-parityfec"
	// TextCacheManifest cache-manifest mime type.
	TextCacheManifest = "text/cache-manifest"
	// TextCalendar calendar mime type.
	TextCalendar = "text/calendar"
	// TextCql cql mime type.
	TextCql = "text/cql"
	// TextCqlExpression cql-expression mime type.
	TextCqlExpression = "text/cql-expression"
	// TextCqlIdentifier cql-identifier mime type.
	TextCqlIdentifier = "text/cql-identifier"
	// TextCSS css mime type.
	TextCSS = "text/css"
	// TextCsv csv mime type.
	TextCsv = "text/csv"
	// TextCsvSchema csv-schema mime type.
	TextCsvSchema = "text/csv-schema"
	// TextDirectoryDeprecatedByRfc6350 directory - DEPRECATED by RFC6350 mime type.
	TextDirectoryDeprecatedByRfc6350 = "text/directory"
	// TextDNS dns mime type.
	TextDNS = "text/dns"
	// TextEcmascriptObsoletedInFavorOfTextJavascript ecmascript (OBSOLETED in favor of text/javascript) mime type.
	TextEcmascriptObsoletedInFavorOfTextJavascript = "text/ecmascript"
	// TextEncaprtp encaprtp mime type.
	TextEncaprtp = "text/encaprtp"
	// TextEnriched enriched mime type.
	TextEnriched = "text/enriched"
	// TextExample example mime type.
	TextExample = "text/example"
	// TextFhirpath fhirpath mime type.
	TextFhirpath = "text/fhirpath"
	// TextFlexfec flexfec mime type.
	TextFlexfec = "text/flexfec"
	// TextFwdred fwdred mime type.
	TextFwdred = "text/fwdred"
	// TextGff3 gff3 mime type.
	TextGff3 = "text/gff3"
	// TextGrammarRefList grammar-ref-list mime type.
	TextGrammarRefList = "text/grammar-ref-list"
	// TextHl7v2 hl7v2 mime type.
	TextHl7v2 = "text/hl7v2"
	// TextHTML html mime type.
	TextHTML = "text/html"
	// TextJavascript javascript mime type.
	TextJavascript = "text/javascript"
	// TextJcrCnd jcr-cnd mime type.
	TextJcrCnd = "text/jcr-cnd"
	// TextMarkdown markdown mime type.
	TextMarkdown = "text/markdown"
	// TextMizar mizar mime type.
	TextMizar = "text/mizar"
	// TextN3 n3 mime type.
	TextN3 = "text/n3"
	// TextOrg org mime type.
	TextOrg = "text/org"
	// TextParameters parameters mime type.
	TextParameters = "text/parameters"
	// TextParityfec parityfec mime type.
	TextParityfec = "text/parityfec"
	// TextPlain plain mime type.
	TextPlain = "text/plain"
	// TextProvenanceNotation provenance-notation mime type.
	TextProvenanceNotation = "text/provenance-notation"
	// TextPrsFallensteinRst prs.fallenstein.rst mime type.
	TextPrsFallensteinRst = "text/prs.fallenstein.rst"
	// TextPrsLinesTag prs.lines.tag mime type.
	TextPrsLinesTag = "text/prs.lines.tag"
	// TextPrsPropLogic prs.prop.logic mime type.
	TextPrsPropLogic = "text/prs.prop.logic"
	// TextPrsTexi prs.texi mime type.
	TextPrsTexi = "text/prs.texi"
	// TextRaptorfec raptorfec mime type.
	TextRaptorfec = "text/raptorfec"
	// TextRed RED mime type.
	TextRed = "text/RED"
	// TextRfc822Headers rfc822-headers mime type.
	TextRfc822Headers = "text/rfc822-headers"
	// TextRichtext richtext mime type.
	TextRichtext = "text/richtext"
	// TextRtf rtf mime type.
	TextRtf = "text/rtf"
	// TextRtpEncAescm128 rtp-enc-aescm128 mime type.
	TextRtpEncAescm128 = "text/rtp-enc-aescm128"
	// TextRtploopback rtploopback mime type.
	TextRtploopback = "text/rtploopback"
	// TextRtx rtx mime type.
	TextRtx = "text/rtx"
	// TextSgml SGML mime type.
	TextSgml = "text/SGML"
	// TextShaclc shaclc mime type.
	TextShaclc = "text/shaclc"
	// TextShex shex mime type.
	TextShex = "text/shex"
	// TextSpdx spdx mime type.
	TextSpdx = "text/spdx"
	// TextStrings strings mime type.
	TextStrings = "text/strings"
	// TextT140 t140 mime type.
	TextT140 = "text/t140"
	// TextTabSeparatedValues tab-separated-values mime type.
	TextTabSeparatedValues = "text/tab-separated-values"
	// TextTroff troff mime type.
	TextTroff = "text/troff"
	// TextTurtle turtle mime type.
	TextTurtle = "text/turtle"
	// TextUlpfec ulpfec mime type.
	TextUlpfec = "text/ulpfec"
	// TextURIList uri-list mime type.
	TextURIList = "text/uri-list"
	// TextVcard vcard mime type.
	TextVcard = "text/vcard"
	// TextVndA vnd.a mime type.
	TextVndA = "text/vnd.a"
	// TextVndAbc vnd.abc mime type.
	TextVndAbc = "text/vnd.abc"
	// TextVndASCIIArt vnd.ascii-art mime type.
	TextVndASCIIArt = "text/vnd.ascii-art"
	// TextVndCurl vnd.curl mime type.
	TextVndCurl = "text/vnd.curl"
	// TextVndDebianCopyright vnd.debian.copyright mime type.
	TextVndDebianCopyright = "text/vnd.debian.copyright"
	// TextVndDmClientScript vnd.DMClientScript mime type.
	TextVndDmClientScript = "text/vnd.DMClientScript"
	// TextVndDvbSubtitle vnd.dvb.subtitle mime type.
	TextVndDvbSubtitle = "text/vnd.dvb.subtitle"
	// TextVndEsmertecThemeDescriptor vnd.esmertec.theme-descriptor mime type.
	TextVndEsmertecThemeDescriptor = "text/vnd.esmertec.theme-descriptor"
	// TextVndExchangeable vnd.exchangeable mime type.
	TextVndExchangeable = "text/vnd.exchangeable"
	// TextVndFamilysearchGedcom vnd.familysearch.gedcom mime type.
	TextVndFamilysearchGedcom = "text/vnd.familysearch.gedcom"
	// TextVndFiclabFlt vnd.ficlab.flt mime type.
	TextVndFiclabFlt = "text/vnd.ficlab.flt"
	// TextVndFly vnd.fly mime type.
	TextVndFly = "text/vnd.fly"
	// TextVndFmiFlexstor vnd.fmi.flexstor mime type.
	TextVndFmiFlexstor = "text/vnd.fmi.flexstor"
	// TextVndGml vnd.gml mime type.
	TextVndGml = "text/vnd.gml"
	// TextVndGraphviz vnd.graphviz mime type.
	TextVndGraphviz = "text/vnd.graphviz"
	// TextVndHans vnd.hans mime type.
	TextVndHans = "text/vnd.hans"
	// TextVndHgl vnd.hgl mime type.
	TextVndHgl = "text/vnd.hgl"
	// TextVndIn3d3dml vnd.in3d.3dml mime type.
	TextVndIn3d3dml = "text/vnd.in3d.3dml"
	// TextVndIn3dSpot vnd.in3d.spot mime type.
	TextVndIn3dSpot = "text/vnd.in3d.spot"
	// TextVndIptcNewsMl vnd.IPTC.NewsML mime type.
	TextVndIptcNewsMl = "text/vnd.IPTC.NewsML"
	// TextVndIptcNitf vnd.IPTC.NITF mime type.
	TextVndIptcNitf = "text/vnd.IPTC.NITF"
	// TextVndLatexZ vnd.latex-z mime type.
	TextVndLatexZ = "text/vnd.latex-z"
	// TextVndMotorolaReflex vnd.motorola.reflex mime type.
	TextVndMotorolaReflex = "text/vnd.motorola.reflex"
	// TextVndMsMediapackage vnd.ms-mediapackage mime type.
	TextVndMsMediapackage = "text/vnd.ms-mediapackage"
	// TextVndNet2phoneCommcenterCommand vnd.net2phone.commcenter.command mime type.
	TextVndNet2phoneCommcenterCommand = "text/vnd.net2phone.commcenter.command"
	// TextVndRadisysMsmlBasicLayout vnd.radisys.msml-basic-layout mime type.
	TextVndRadisysMsmlBasicLayout = "text/vnd.radisys.msml-basic-layout"
	// TextVndSenxWarpscript vnd.senx.warpscript mime type.
	TextVndSenxWarpscript = "text/vnd.senx.warpscript"
	// TextVndSiUricatalogueObsoletedByRequest vnd.si.uricatalogue (OBSOLETED by request) mime type.
	TextVndSiUricatalogueObsoletedByRequest = "text/vnd.si.uricatalogue"
	// TextVndSunJ2meAppDescriptor vnd.sun.j2me.app-descriptor mime type.
	TextVndSunJ2meAppDescriptor = "text/vnd.sun.j2me.app-descriptor"
	// TextVndSosi vnd.sosi mime type.
	TextVndSosi = "text/vnd.sosi"
	// TextVndTypst vnd.typst mime type.
	TextVndTypst = "text/vnd.typst"
	// TextVndTrolltechLinguist vnd.trolltech.linguist mime type.
	TextVndTrolltechLinguist = "text/vnd.trolltech.linguist"
	// TextVndVcf vnd.vcf mime type.
	TextVndVcf = "text/vnd.vcf"
	// TextVndWapSi vnd.wap.si mime type.
	TextVndWapSi = "text/vnd.wap.si"
	// TextVndWapSl vnd.wap.sl mime type.
	TextVndWapSl = "text/vnd.wap.sl"
	// TextVndWapWml vnd.wap.wml mime type.
	TextVndWapWml = "text/vnd.wap.wml"
	// TextVndWapWmlscript vnd.wap.wmlscript mime type.
	TextVndWapWmlscript = "text/vnd.wap.wmlscript"
	// TextVndZooKcl vnd.zoo.kcl mime type.
	TextVndZooKcl = "text/vnd.zoo.kcl"
	// TextVtt vtt mime type.
	TextVtt = "text/vtt"
	// TextWgsl wgsl mime type.
	TextWgsl = "text/wgsl"
	// TextXML xml mime type.
	TextXML = "text/xml"
	// TextXMLExternalParsedEntity xml-external-parsed-entity mime type.
	TextXMLExternalParsedEntity = "text/xml-external-parsed-entity"
)

// IsText checks if the mime types is text.
func IsText(mt string) bool {
	switch mt {
	case "text/1d-interleaved-parityfec":
		return true
	case "text/RED":
		return true
	case "text/SGML":
		return true
	case "text/cache-manifest":
		return true
	case "text/calendar":
		return true
	case "text/cql":
		return true
	case "text/cql-expression":
		return true
	case "text/cql-identifier":
		return true
	case "text/css":
		return true
	case "text/csv":
		return true
	case "text/csv-schema":
		return true
	case "text/directory":
		return true
	case "text/dns":
		return true
	case "text/ecmascript":
		return true
	case "text/encaprtp":
		return true
	case "text/enriched":
		return true
	case "text/example":
		return true
	case "text/fhirpath":
		return true
	case "text/flexfec":
		return true
	case "text/fwdred":
		return true
	case "text/gff3":
		return true
	case "text/grammar-ref-list":
		return true
	case "text/hl7v2":
		return true
	case "text/html":
		return true
	case "text/javascript":
		return true
	case "text/jcr-cnd":
		return true
	case "text/markdown":
		return true
	case "text/mizar":
		return true
	case "text/n3":
		return true
	case "text/org":
		return true
	case "text/parameters":
		return true
	case "text/parityfec":
		return true
	case "text/plain":
		return true
	case "text/provenance-notation":
		return true
	case "text/prs.fallenstein.rst":
		return true
	case "text/prs.lines.tag":
		return true
	case "text/prs.prop.logic":
		return true
	case "text/prs.texi":
		return true
	case "text/raptorfec":
		return true
	case "text/rfc822-headers":
		return true
	case "text/richtext":
		return true
	case "text/rtf":
		return true
	case "text/rtp-enc-aescm128":
		return true
	case "text/rtploopback":
		return true
	case "text/rtx":
		return true
	case "text/shaclc":
		return true
	case "text/shex":
		return true
	case "text/spdx":
		return true
	case "text/strings":
		return true
	case "text/t140":
		return true
	case "text/tab-separated-values":
		return true
	case "text/troff":
		return true
	case "text/turtle":
		return true
	case "text/ulpfec":
		return true
	case "text/uri-list":
		return true
	case "text/vcard":
		return true
	case "text/vnd.DMClientScript":
		return true
	case "text/vnd.IPTC.NITF":
		return true
	case "text/vnd.IPTC.NewsML":
		return true
	case "text/vnd.a":
		return true
	case "text/vnd.abc":
		return true
	case "text/vnd.ascii-art":
		return true
	case "text/vnd.curl":
		return true
	case "text/vnd.debian.copyright":
		return true
	case "text/vnd.dvb.subtitle":
		return true
	case "text/vnd.esmertec.theme-descriptor":
		return true
	case "text/vnd.exchangeable":
		return true
	case "text/vnd.familysearch.gedcom":
		return true
	case "text/vnd.ficlab.flt":
		return true
	case "text/vnd.fly":
		return true
	case "text/vnd.fmi.flexstor":
		return true
	case "text/vnd.gml":
		return true
	case "text/vnd.graphviz":
		return true
	case "text/vnd.hans":
		return true
	case "text/vnd.hgl":
		return true
	case "text/vnd.in3d.3dml":
		return true
	case "text/vnd.in3d.spot":
		return true
	case "text/vnd.latex-z":
		return true
	case "text/vnd.motorola.reflex":
		return true
	case "text/vnd.ms-mediapackage":
		return true
	case "text/vnd.net2phone.commcenter.command":
		return true
	case "text/vnd.radisys.msml-basic-layout":
		return true
	case "text/vnd.senx.warpscript":
		return true
	case "text/vnd.si.uricatalogue":
		return true
	case "text/vnd.sosi":
		return true
	case "text/vnd.sun.j2me.app-descriptor":
		return true
	case "text/vnd.trolltech.linguist":
		return true
	case "text/vnd.typst":
		return true
	case "text/vnd.vcf":
		return true
	case "text/vnd.wap.si":
		return true
	case "text/vnd.wap.sl":
		return true
	case "text/vnd.wap.wml":
		return true
	case "text/vnd.wap.wmlscript":
		return true
	case "text/vnd.zoo.kcl":
		return true
	case "text/vtt":
		return true
	case "text/wgsl":
		return true
	case "text/xml":
		return true
	case "text/xml-external-parsed-entity":
		return true
	default:
		return false
	}
}
